### ISSUE TITLE
CollisionManager 300MB of memory

### ISSUE THREAD

**Issue by rlgenesis** [apollo-rsps/apollo#377] opened 2018-01-20 09:49 UTC
l:241, World.java takes up almost 300MB of RAM. This code specifically

```
collisionManager.build(false);
```

**Comment by garyttierney** [comment] 2018-01-20 16:44
Duplicate of https://github.com/apollo-rsps/apollo/issues/328

**Closed by garyttierney** 2018-01-20 16:44 UTC
