### ISSUE TITLE
How do I compile this

### ISSUE THREAD

**Issue by Rottweiler** [apollo-rsps/apollo#312] opened 2017-02-28 00:11 UTC
How do I compile this to get a functioning server?

**Comment by rlgenesis** [comment] 2017-04-25 07:15
Should take a look at issue #280

**Comment by Major-** [comment] 2017-05-04 17:53
Closing as a duplicate of #280 (general gist is install gradle and then `gradle run` from the apollo directory)

**Closed by Major-** 2017-05-04 17:53 UTC
