### ISSUE TITLE
::clearnpcs command is broken

### ISSUE THREAD

**Issue by WizardJesse1** [apollo-rsps/apollo#142] opened 2016-01-31 06:52 UTC
If you try to do ::clearnpcs it does remove the npcs but it gives the following error:

```java
java.lang.IllegalArgumentException: Entity (Npc{id=1, name=Man}) belongs in (Region{coordinates=RegionCoordinates{x=381, y=382}}) but does not exist.
	at org.apollo.game.model.area.Region.removeEntity(org/apollo/game/model/area/Region.java:286)
	at org.apollo.game.model.World.unregister(org/apollo/game/model/World.java:315)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at RUBY.block in (root)(C:\Users\Jess3\Downloads\apollo-master\apollo-master\.\data\plugins\cmd\npc\spawn.rb:66)
	at RUBY.each(uri:classloader:/jruby/java/java_ext/java.lang.rb:12)
	at RUBY.block in (root)(C:\Users\Jess3\Downloads\apollo-master\apollo-master\.\data\plugins\cmd\npc\spawn.rb:66)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:308)
	at RUBY.execute(C:\Users\Jess3\Downloads\apollo-master\apollo-master\.\data\plugins\bootstrap.rb:52)
	at org.apollo.game.command.CommandListener.executePrivileged(org/apollo/game/command/CommandListener.java:51)
	at org.apollo.game.command.CommandDispatcher.dispatch(org/apollo/game/command/CommandDispatcher.java:39)
	at org.apollo.game.message.handler.CommandMessageHandler.handle(org/apollo/game/message/handler/CommandMessageHandler.java:34)
	at org.apollo.game.message.handler.CommandMessageHandler.handle(org/apollo/game/message/handler/CommandMessageHandler.java:14)
	at org.apollo.game.message.handler.MessageHandlerChain.notify(org/apollo/game/message/handler/MessageHandlerChain.java:57)
	at org.apollo.game.message.handler.MessageHandlerChainSet.notify(org/apollo/game/message/handler/MessageHandlerChainSet.java:45)
	at org.apollo.game.session.GameSession.handlePendingMessages(org/apollo/game/session/GameSession.java:96)
	at org.apollo.game.service.GameService.pulse(org/apollo/game/service/GameService.java:162)
	at org.apollo.game.GamePulseHandler.run(org/apollo/game/GamePulseHandler.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(java/util/concurrent/Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(java/util/concurrent/FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(java/util/concurrent/ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java/util/concurrent/ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(java/lang/Thread.java:745)
```

**Comment by Major-** [comment] 2016-01-31 07:31
This is potentially very bad... cc @ryleykimmel

**Comment by thispixel** [comment] 2016-01-31 17:13
https://github.com/apollo-rsps/apollo/blob/master/game/src/main/org/apollo/game/model/area/Region.java#L283

That set contains the npc being removed, so the npc has been registered correctly in the region, however if you do

`local.contains(entity)`

it returns false, so i'm guessing this issue is related to equals() / hashcode()

**Comment by garyttierney** [comment] 2016-01-31 17:35
@ryleykimmel @Major- possibly have this fixed locally. Wouldn't look to much into it 'til I can confirm.

**Comment by Major-** [comment] 2016-02-01 04:03
That sounds likely @thispixel; not sure if simply removing it from the region before the repository is adequate... seems like quite a fragile fix

**Comment by ryleykimmel** [comment] 2016-02-04 00:08
@Major- not really a fragile fix, why should any Mob be set inactive (index = -1) before pre-unregister tasks have completed?

Also letting MobRepository#remove return a boolean is stupid, there really isn't a way to recover from it or do something else. Throwing an exception is likely the better option as something is clearly wrong if the Mob index does not match the expected position in the repository.

**Comment by Major-** [comment] 2016-02-04 15:21
It's fragile because reordering two seemingly-independent lines of code will break the behaviour.

I'm not opposed to doing it like that though, but it needs unit tests too.

**Comment by ryleykimmel** [comment] 2016-02-05 21:21
@Major- close this please

**Comment by WizardJesse1** [comment] 2016-02-05 22:38
@ryleykimmel if u do the command with this fix you can't walk and it says

```
WARNING: Too many messages in queue for game session, dropping...
Feb 05, 2016 5:37:56 PM org.apollo.game.session.GameSession messageReceived
WARNING: Too many messages in queue for game session, dropping...
```

**Comment by ryleykimmel** [comment] 2016-02-06 07:37
Curious to why we queue inbound messages anyway, why not handle them instantly? @Major- @garyttierney

**Comment by Major-** [comment] 2016-02-06 09:29
Passing the decoded result (i.e. `XMessage`) into the game thread requries locking; decoding them all at once means we only have to acquire the lock once, instead of every time we get a message.

**Comment by ryleykimmel** [comment] 2016-02-06 19:40
There should be a better way to do that, dropping legitimate messages after 10 is strange

**Comment by ryleykimmel** [comment] 2016-02-06 19:51
Also looked into this, we can move that from the game thread and process them in the GameSession alone instantly.

**Comment by Major-** [comment] 2016-02-06 20:06
10 is left over from the original release, so I think we can definitely bump this up (20 or 25 should be fine).

**Closed** 2016-02-09 21:13 UTC
Labels: bug
