### ISSUE TITLE
GroundItem: Region problem on item drop?

### ISSUE THREAD

**Issue by rlgenesis** [apollo-rsps/apollo#316] opened 2017-04-25 21:03 UTC
Not sure but I think regions are being detected incorrectly. Basically if you log in and type ::drop command, the GroundItem spawns onto the table. You can also go to any region and type ::drop, the item never spawns under you. 

http://pix.toile-libre.org/upload/original/1493154091.png

Here is the command (added into cmd/item/item.rb)

```ruby
java_import 'org.apollo.game.model.entity.GroundItem'

on :command, :drop, RIGHTS_ADMIN do |player, command|
  @item = GroundItem.dropped($world, player.position, Item.new(1), player) 
  $world.spawn(@item) 
end```

**Comment by WizardJesse1** [comment] 2017-04-27 20:17
Ya I looked into it a little bit and the calculations are off for region.

@garyttierney

**Comment by garyttierney** [comment] 2017-04-27 20:26
@WizardJesse1 do you mean the grouped region update calculations?  Strange they'd be broken since objects and projectiles, among other things, rely on those.

CC @Major-

**Comment by WizardJesse1** [comment] 2017-04-28 14:09
@garyttierney in region coordinates class the calculations for absolute x & y are off slightly which is why it happens its off by 6 for x & y

**Comment by Major-** [comment] 2017-05-03 12:47
Definitely looks broken, probably something to do with the positionOffset bitshift stuff in the message encoder

**Comment by rlgenesis** [comment] 2017-05-09 06:18
Anyone have a fix for this?

**Comment by garyttierney** [comment] 2017-05-09 16:36
@Major- Hmm, not sure about that.  Works fine for objects and projectiles which would use the same grouped region updates.

**Comment by xgenesisr** [comment] 2017-05-19 04:54
Literally the only thing preventing me from working on Apollo ;(

**Comment by WizardJesse1** [comment] 2017-05-21 07:06
@xgenesisr sorry that this is preventing you :( I know why this issue happens but with how major wrote it and with gary telling me in the past that it was fine with projectiles/game objects has me lost @garyttierney or @Major- will probably have to do it when they are free

**Comment by garyttierney** [comment] 2017-05-23 00:54
This is fixed in #318, however, see the below note.

The behaviour of dropped items with the current encoder is rather strange in my opinion.  Instead of showing an item only to the player who dropped it, it shows it to anyone but the person who dropped it.  See this snippet of code from the reference client:

```java
		if (opcode == 106) { // add ground item dropped by player
			int offset = buf.getByteA();
			int x = placementX + (offset >> 4 & 7);
			int y = placementY + (offset & 7);
			int amount = buf.getLEShortA();
			int id = buf.getShortA();
			int playerId = buf.getShortA();

			if (x >= 0 && y >= 0 && x < 104 && y < 104 && playerId != ourPlayerId) {
				GroundItem item = new GroundItem();
				item.id = id;
				item.amount = amount;
				if (groundItems[plane][x][y] == null) {
					groundItems[plane][x][y] = new LinkedList();
				}
				groundItems[plane][x][y].addLast(item);
				updateGroundItems(x, y);
			}
			return;
		}
```

It might be the case that this was a refactoring mistake.  Can anyone confirm?  cc @Major-, also reopening for that purpose.

**Closed** 2017-05-23 10:40 UTC
Labels: bug, high priority, medium

**Comment by Major-** [comment] 2017-05-23 10:42
As you can clearly see from 0559c40 this was hardly a complicated bug to solve, it just required a bit of effort to look over the code. If you're really that keen to use a project then you could've spent some time to try and identify the bug yourself - maintainers have a limited amount of it, just like everyone else.

**Comment by xgenesisr** [comment] 2017-05-23 18:07
I did look over the source, not sure what you're talking about.

**Comment by xgenesisr** [comment] 2017-05-23 18:50
@Major-  I'm not sure where you're getting your information from to assume that I didn't look through the source code. I looked through AddGlobalTileItemMessageEncoder, Region, GroupedRegionUpdateMessage, RegionCoordinate @absoluteX & @absoluteY, UpdateOperation.getPositionOffset , I went as far as looking through the client code at packet 215 to check what coordinates were being sent, and I was also mislead by your own comment which suggested it being "position bitshift stuff" which I also looked at.

@Major- Just because I wasn't missed 1 class, doesn't mean that I didn't actually try to identify the bug so I could help contribute to the project. The fact that you would even assume that and say "if you're really that keen to use a project" is rather insulting and I thought you were a bigger person than that. Fact of the matter is, this problem wasn't in Graham's original Apollo source, you are the one that pushed an update with a major bug in it. In the Apollo thread it says one way of contributing is by helping find problems, and when someone does just that you're going to insist I didn't "try hard enough to use the source"?

Anyway have a good one, doubt I'll be picking this up at this point. If I do will just probably fork it.

**Comment by garyttierney** [comment] 2017-05-23 19:42
Attributing blame really serves no purpose; we should be focusing on fixing the issues instead.  The real facts are that since Apollo was originally released numerous problems have been solved and new features added.  With new code comes new bugs, which is completely expected and inevitable.  If we start to see 50 new bugs introduced for every 1 new feature then it becomes a problem, but that's not happening.  In the future we should look at better [automated] testing to catch these trivial issues early.

> Fact of the matter is, this problem wasn't in Graham's original Apollo source, you are the one that pushed an update with a major bug in it.

I'll give you that, but consider that this bug was isolated to ground items and the original release of Apollo didn't support ground items.  As explained, bugs are introduced with new features.  Fortunately not that often.

Addressing this particular bug, for me, was as simple as this process:

* Set breakpoint in packet 215 handler in the client
* Send a GroundItem packet and record the dx and dy calculated in servers getPositionOffset()
  * dx = 5
  * dy = 1
* Record the decoded dx and dy in packet 215 handler breakpoint
  * offset = 1
  * dx = 0 // (offset >> 4 & 7)
  * dy = 1 // (offset & 7)
* Server dx,dy and client dx,dy don't match.  Check offset value in AddGlobalTileItemMessageEncoder
* Offset value in AddGlobalTileItemMessageEncoder matches client value, check for calls to the SendPublicTileItemMessage constructor
  * offset = 1
* SendPublicTileItemMessage constructor in ItemUpdateOperation has wrong argument order
* **Solved!**

There wasn't anything particularly complicated about this and it's standard procedure using a debugger which can handle stepping through code.  I firmly believe that anyone, given some time and the correct documentation, would be able to solve this in the same manner that I did.  You looked in all the same places as me and just happened to miss what I seen using debugging tools.  I think adding a few wiki pages on practical debugging might help some users with that.

Note: spending some effort on identifying the bug doesn't necessarily mean implementing the fix and sending the pull request.  Sharing details of what you've seen yourself when trying to debug the issue on the relevant GitHub issue is a massive help to maintainers that we're incredibly grateful for, in addition to the bug reports themselves.

**Comment by Major-** [comment] 2017-05-23 20:06
> I'm not sure where you're getting your information from to assume that I didn't look through the source code. ... Just because I missed 1 class, doesn't mean that I didn't actually try to identify the bug so I could help contribute to the project. 

Fair enough, I did not mean to imply that you had put no effort in at all - however, you will of course be aware that no matter how much code you looked through, if you didn't fix it then the person who did had to look through even more. So you can revise what I originally said to be "You didn't put enough effort in, and instead relied on someone else to".

>Fact of the matter is, this problem wasn't in Graham's original Apollo source, you are the one that pushed an update with a major bug in it. 

This is correct, although I'm not sure what you're getting at here; yes I introduced this bug, and yes it is stupid. Sometimes I make stupid mistakes, just like everyone else. This does not mean I have not put immense time and effort into this project.

>In the Apollo thread it says one way of contributing is by helping find problems

It is, and people who open issues and report bugs are very valuable to any project, apollo included.

>and when someone does just that you're going to insist I didn't "try hard enough to use the source"?

This is either a misinterpretation or an outright misrepresentation of what I said (particularly with the non-existent quote), so let me be clear: comments that serve no purpose other than to hurry maintainers up are conceited and rude, and if you post one you should not be surprised when you are reminded that other peoples time is also valuable. The issue is great, the image is great, the sample code is great - if every issue on Github was like this one then software would be of much higher quality.
