### ISSUE TITLE
Make inventory code atomic (a.k.a prevent losing items during trade)

### ISSUE THREAD

**Issue by Lmctruck30** [apollo-rsps/apollo#307] opened 2016-12-10 19:16 UTC
Just as an FYI when we do implement combat/trade on this when a player disconnects via internet connection or force closing the client it will cause issues with dropped items in combat or trading items getting stuck on the interface causing that player to lose those items. This can apply to things more than combat and trade.

**Comment by Lmctruck30** [comment] 2016-12-10 21:52
@garyttierney @ryleykimmel Ideas on how to fix this properly?

**Comment by garyttierney** [comment] 2016-12-11 02:04
@ryleykimmel did some work on atomic inventory transactions.  Not sure what the status of that was.

**Comment by garyttierney** [comment] 2016-12-16 18:29
Closing as a duplicate of #233.

**Closed by garyttierney** 2016-12-16 18:29 UTC
